### PR TITLE
Add support for disabling copy and paste for issue #36

### PR DESCRIPTION
**Pull request by ION28**

### CODE REVIEW

**Comment by ION28** [comment]
Also just wanted to say that this ansible module has been an absolute lifesaver - thank you so much for your continued maintenance of the project

**Comment by ION28** [comment]
@pescobar Wondering if you could review this when you get a chance & possibly considering making a new release available in ansible-galaxy? It should be a pretty small fix and it has passed my local testing. It won't let me start the Github workflow on the PR though since I'm not a contributor.

**Comment by pescobar** [comment]
Sorry for the delay. I missed this one because of the Christmas break. I will publish a new release tomorrow

**Comment by ION28** [comment]
No problem, it's a busy time. Thank you so much for your help & maintaining this project for the community!

**Pull request merged**
