### PR TITLE
WIP: new module to administer connections groups

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by pescobar** [comment]
docs for this new module 

```
> SCICORE.GUACAMOLE.GUACAMOLE_CONNECTIONS_GROUP    (/home/pablo/ansible/ansible-playbook-guacamole-api/collections/ansible_collections/scicore/guacamole/plugins/modules/guacamole_connections_group.py)

        Add or remove guacamole connections groups.

OPTIONS (= is mandatory):

= auth_password
        Guacamole admin user password to login to the API

        type: str

= auth_username
        Guacamole admin user to login to the API

        type: str

= base_url
        Url to access the guacamole API
        (Aliases: url)
        type: str

- enable_session_affinity
        Enable session affinity for this group
        [Default: (null)]
        type: bool

- force_deletion
        Force deletion of the group even if it has child connections
        [Default: False]
        type: bool

= group_name
        Group name to create

        type: str

- group_type
        Choose the group type
        (Choices: ORGANIZATIONAL, BALANCING)[Default: ORGANIZATIONAL]
        type: str

- max_connections
        Max connections in this group
        [Default: (null)]
        type: int

- max_connections_per_user
        Max connections per user in this group
        [Default: (null)]
        type: int

- parent_group
        Parent group in case this is a sub-group
        (Aliases: parentIdentifier)[Default: ROOT]
        type: str

- state
        Create or delete the connections group?
        (Choices: present, absent)[Default: present]
        type: str

- validate_certs
        Validate ssl certs?
        [Default: True]
        type: bool


AUTHOR: Pablo Escobar Lopez (@pescobar)

METADATA:
  metadata_version: '1.1'
  status:
  - preview
  supported_by: community


VERSION_ADDED_COLLECTION: scicore.guacamole

EXAMPLES:

- name: Create a new group "group_3"
  scicore.guacamole.guacamole_connections_group:
    base_url: http://localhost/guacamole
    auth_username: guacadmin
    auth_password: guacadmin
    group_name: group_3


RETURN VALUES:
- connections_group_info
        Information about the created or updated connections group

        returned: always
        type: dict

- message
        Some extra info about what the module did

        returned: always
        type: str
```

**Comment by sbraz** [comment]
@pescobar sorry I haven't had time to check this yet but I will do it ASAP. I see you've already merged this so I will only let you know if something is wrong.

**Comment by pescobar** [comment]
@sbraz latest published version in ansible galaxy includes this module. Give it a try and let me know if you experience any issues.

**Comment by sbraz** [comment]
@pescobar thanks, we tested it yesterday and it works fine.

**Pull request merged**
